{
    'name': 'Academic Management',
    'version': '1.0',
    'summary': 'Modul untuk mengelola Course dan Session',
    'category': 'Education',
    'author': 'Internal',
    'depends': ['base', 'contacts'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/report_session.xml',
        'report/report_session_template.xml',
        'report/report_course.xml',
        'report/report_course_template.xml',
        'views/academic_views.xml',
        'views/session.xml',
        'views/wizard_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}